version: '2'
services:
  postgresql:
    image: 'postgres:11.4'
    environment:
      - POSTGRES_USER=auctDev
      - POSTGRES_PASSWORD=auctDev#2019
    ports:
      - 15432:5432
      - 15432:5432/udp
    volumes:
      - /opt/var/lib/postgresql/data:/var/lib/postgresql/data
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms128m
      - discovery.type=single-node
    ports:
      - 9200:9200
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  jhipster-logstash:
    image: jhipster/jhipster-logstash:v4.1.0
    environment:
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSTASH_DEBUG=false
    ports:
      - 5000:5000
      - 5000:5000/udp
  jhipster-zipkin:
    image: jhipster/jhipster-zipkin:v4.1.0
    ports:
      - 9411:9411
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m
      - ES_HOSTS=http://elasticsearch:9200
      - ZIPKIN_UI_LOGS_URL=http://localhost:5601/app/kibana#/discover/d0682f20-e0e9-11e7-9c68-0b9a0f0c183c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(X-B3-TraceId,app_name,level,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-*',key:X-B3-TraceId,negate:!f,params:(query:'trace',type:phrase),type:phrase,value:'trace'),query:(match:(X-B3-TraceId:(query:'{traceId}',type:phrase))))),index:'logs-*',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))
